_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.9.21
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-x86_64
batch_size:
    value: 4096
data:
    value: null
dropout:
    value: 0.009
epochs:
    value: 200
final_dropout:
    value: 0.1
loss:
    value: ce
lr:
    value: 0.006
model:
    value: gat
n_gnn_layers:
    value: 2
n_heads:
    value: 4
n_hidden:
    value: 64
num_neighbors:
    value:
        - 100
        - 100
w_ce1:
    value: 1
w_ce2:
    value: 6
