_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.0
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-x86_64
batch_size:
    value: 8192
data:
    value: null
dropout:
    value: 0.009
epochs:
    value: 100
final_dropout:
    value: 0.1
loss:
    value: ce
lr:
    value: 0.006
model:
    value: gat
n_gnn_layers:
    value: 2
n_heads:
    value: 4
n_hidden:
    value: 64
num_neighbors:
    value:
        - 100
        - 100
w_ce1:
    value: 1
w_ce2:
    value: 6
