_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-x86_64
batch_size:
    value: 8192
data:
    value: null
dropout:
    value: null
epochs:
    value: 100
final_dropout:
    value: null
loss:
    value: ce
lr:
    value: null
model:
    value: git
n_gnn_layers:
    value: null
n_heads:
    value: null
n_hidden:
    value: null
num_neighbors:
    value:
        - 100
        - 100
w_ce1:
    value: null
w_ce2:
    value: null
